export const WS_USER_CONNECTION_START = "WS_USER_CONNECTION_START";
export const WS_USER_CONNECTION_ERROR = "WS_USER_CONNECTION_ERROR";
export const WS_USER_CONNECTION_CLOSE = "WS_USER_CONNECTION_CLOSE";
export const WS_USER_GET_MESSAGE = "WS_USER_GET_MESSAGE";

export type TWSUserActions =
  | typeof WS_USER_CONNECTION_START
  | typeof WS_USER_CONNECTION_ERROR
  | typeof WS_USER_CONNECTION_CLOSE
  | typeof WS_USER_GET_MESSAGE;
